FROM basshub/php:7.4.33 AS base

ENV PROJECT_ROOT /var/www/html
WORKDIR $PROJECT_ROOT




FROM base AS builder

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

EXPOSE 80

CMD php-fpm -D; nginx -g 'daemon off;'
