FROM basshub/php:7.4.33 AS base

ENV PROJECT_ROOT /var/www/html
WORKDIR $PROJECT_ROOT




FROM base AS builder

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN set -eux; \
        apk add --no-cache --virtual .build-deps \
            autoconf \
            g++ \
            make

RUN pecl install xdebug-3.1.6; \
    docker-php-ext-enable xdebug; \
    apk del --no-network .build-deps;

COPY docker-php-ext-xdebug.ini $PHP_INI_DIR/conf.d/

EXPOSE 80

CMD php-fpm -D; nginx -g 'daemon off;'
