FROM php:7.4-fpm-alpine

ENV PROJECT_ROOT /var/www/html
WORKDIR $PROJECT_ROOT

RUN apk update
RUN apk upgrade

RUN apk add caddy

RUN set -eux; \
    apk add --no-cache \
        libpng \
        zip \
        libzip-dev \
        freetype-dev \
        libjpeg-turbo-dev \
        libpng-dev \
        libwebp-dev \
    ; \
    docker-php-ext-configure \
        gd \
        --with-freetype \
        --with-jpeg \
        --with-webp \
    ; \
    docker-php-ext-install \
        gd \
        mysqli \
        pdo \
        pdo_mysql \
        zip \
    ; \
    docker-php-ext-enable \
        pdo_mysql \
    ;


COPY Caddyfile /etc/caddy/Caddyfile
COPY zz-docker.conf /usr/local/etc/php-fpm.d/zz-docker.conf
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# build
COPY --chown=www-data:www-data . $PROJECT_ROOT
RUN composer install

EXPOSE 80

# CMD caddy run --config /etc/caddy/Caddyfile --adapter caddyfile; php-fpm -F -R
CMD crond; php-fpm -D; caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
