name: Manual build PHP

on:
  workflow_dispatch:
    inputs:
      php-version:
        description: Select php version
        required: true
        type: choice
        default: '8.2.7'
        options:
          - '8.2.7'
          - '8.1.20'
          - '7.4.33'

env:
  REGISTRY: basshub/php

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker production
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}
          # flavor: |
          #   latest=false
          tags: |
            type=semver,pattern={{version}},value=${{ github.event.inputs.php-version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ github.event.inputs.php-version }}
            type=semver,pattern={{major}},value=${{ github.event.inputs.php-version }}
          labels: |
            org.opencontainers.image.title=${{ github.event.inputs.php-version }}
            org.opencontainers.image.description=${{ github.event.inputs.php-version }}
            org.opencontainers.image.source=https://github.com/anhkhoa289/anhkhoa289/php/${{ github.event.inputs.php-version }}/Dockerfile
            org.opencontainers.image.url=https://github.com/anhkhoa289/anhkhoa289/php/${{ github.event.inputs.php-version }}/Dockerfile

      - name: Build and push Docker production image
        uses: docker/build-push-action@v4
        with:
          context: anhkhoa289/php/${{ github.event.inputs.php-version }}
          file: ./anhkhoa289/php/${{ github.event.inputs.php-version }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata (tags, labels) for Docker composer
        id: meta-composer
        uses: docker/metadata-action@v4
        env:
          SUFFIX: composer
        with:
          images: ${{ env.REGISTRY }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=${{ env.SUFFIX }}
            type=semver,pattern={{version}},suffix=-${{ env.SUFFIX }},value=${{ github.event.inputs.php-version }}
            type=semver,pattern={{major}}.{{minor}},suffix=-${{ env.SUFFIX }},value=${{ github.event.inputs.php-version }}
            type=semver,pattern={{major}},suffix=-${{ env.SUFFIX }},value=${{ github.event.inputs.php-version }}
          labels: |
            org.opencontainers.image.title=${{ github.event.inputs.php-version }}
            org.opencontainers.image.description=${{ github.event.inputs.php-version }}
            org.opencontainers.image.source=https://github.com/anhkhoa289/anhkhoa289/php/${{ github.event.inputs.php-version }}/Dockerfile
            org.opencontainers.image.url=https://github.com/anhkhoa289/anhkhoa289/php/${{ github.event.inputs.php-version }}/Dockerfile

      - name: Build and push Docker composer image
        uses: docker/build-push-action@v4
        with:
          context: anhkhoa289/php/${{ github.event.inputs.php-version }}
          file: ./anhkhoa289/php/${{ github.event.inputs.php-version }}/Dockerfile.composer
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-composer.outputs.tags }}
          labels: ${{ steps.meta-composer.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata (tags, labels) for Docker development
        id: meta-dev
        uses: docker/metadata-action@v4
        env:
          SUFFIX: dev
        with:
          images: ${{ env.REGISTRY }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=${{ env.SUFFIX }}
            type=semver,pattern={{version}},suffix=-${{ env.SUFFIX }},value=${{ github.event.inputs.php-version }}
            type=semver,pattern={{major}}.{{minor}},suffix=-${{ env.SUFFIX }},value=${{ github.event.inputs.php-version }}
            type=semver,pattern={{major}},suffix=-${{ env.SUFFIX }},value=${{ github.event.inputs.php-version }}
          labels: |
            org.opencontainers.image.title=${{ github.event.inputs.php-version }}
            org.opencontainers.image.description=${{ github.event.inputs.php-version }}
            org.opencontainers.image.source=https://github.com/anhkhoa289/anhkhoa289/php/${{ github.event.inputs.php-version }}/Dockerfile.dev
            org.opencontainers.image.url=https://github.com/anhkhoa289/anhkhoa289/php/${{ github.event.inputs.php-version }}/Dockerfile.dev

      - name: Build and push Docker development image
        uses: docker/build-push-action@v4
        with:
          context: anhkhoa289/php/${{ github.event.inputs.php-version }}
          file: ./anhkhoa289/php/${{ github.event.inputs.php-version }}/Dockerfile.dev
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-dev.outputs.tags }}
          labels: ${{ steps.meta-dev.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata (tags, labels) for Docker laravel
        id: meta-laravel
        uses: docker/metadata-action@v4
        env:
          SUFFIX: laravel
        with:
          images: ${{ env.REGISTRY }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=${{ env.SUFFIX }}
            type=semver,pattern={{version}},suffix=-${{ env.SUFFIX }},value=${{ github.event.inputs.php-version }}
            type=semver,pattern={{major}}.{{minor}},suffix=-${{ env.SUFFIX }},value=${{ github.event.inputs.php-version }}
            type=semver,pattern={{major}},suffix=-${{ env.SUFFIX }},value=${{ github.event.inputs.php-version }}
          labels: |
            org.opencontainers.image.title=${{ github.event.inputs.php-version }}
            org.opencontainers.image.description=${{ github.event.inputs.php-version }}
            org.opencontainers.image.source=https://github.com/anhkhoa289/anhkhoa289/php/${{ github.event.inputs.php-version }}/Dockerfile.laravel
            org.opencontainers.image.url=https://github.com/anhkhoa289/anhkhoa289/php/${{ github.event.inputs.php-version }}/Dockerfile.laravel

      - name: Build and push Docker laravel image
        uses: docker/build-push-action@v4
        with:
          context: anhkhoa289/php/${{ github.event.inputs.php-version }}
          file: ./anhkhoa289/php/${{ github.event.inputs.php-version }}/Dockerfile.laravel
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-laravel.outputs.tags }}
          labels: ${{ steps.meta-laravel.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
