name: Manual build PHP 7

on:
  workflow_dispatch:
    # inputs:
    #   tag:
    #     description: Tag
    #     required: true
    #     type: string
  # ${{ github.event.inputs.tag }}

env:
  PHP_MAJOR: 7
  PHP_VERSION: v7.4.33
  REGISTRY: anhkhoa289/php

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker production
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}},value=${{ env.PHP_VERSION }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.PHP_VERSION }}
            type=semver,pattern={{major}},value=${{ env.PHP_VERSION }}
          labels: |
            org.opencontainers.image.title=${{ env.PHP_MAJOR }}
            org.opencontainers.image.description=${{ env.PHP_MAJOR }}
            org.opencontainers.image.source=https://github.com/anhkhoa289/anhkhoa289/php/${{ env.PHP_MAJOR }}/dockerfile
            org.opencontainers.image.url=https://github.com/anhkhoa289/anhkhoa289/php/${{ env.PHP_MAJOR }}/dockerfile

      - name: Build and push Docker production image
        uses: docker/build-push-action@v4
        with:
          context: anhkhoa289/php/${{ env.PHP_MAJOR }}
          file: ./anhkhoa289/php/${{ env.PHP_MAJOR }}/dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata (tags, labels) for Docker composer
        id: meta-composer
        uses: docker/metadata-action@v4
        env:
          SUFFIX: composer
        with:
          images: ${{ env.REGISTRY }}
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}},suffix=-${{ env.SUFFIX }},value=${{ env.PHP_VERSION }}
            type=semver,pattern={{major}}.{{minor}},suffix=-${{ env.SUFFIX }},value=${{ env.PHP_VERSION }}
            type=semver,pattern={{major}},suffix=-${{ env.SUFFIX }},value=${{ env.PHP_VERSION }}
          labels: |
            org.opencontainers.image.title=${{ env.PHP_MAJOR }}
            org.opencontainers.image.description=${{ env.PHP_MAJOR }}
            org.opencontainers.image.source=https://github.com/anhkhoa289/anhkhoa289/php/${{ env.PHP_MAJOR }}/dockerfile
            org.opencontainers.image.url=https://github.com/anhkhoa289/anhkhoa289/php/${{ env.PHP_MAJOR }}/dockerfile

      - name: Build and push Docker composer image
        uses: docker/build-push-action@v4
        with:
          context: anhkhoa289/php/${{ env.PHP_MAJOR }}
          file: ./anhkhoa289/php/${{ env.PHP_MAJOR }}/dockerfile.composer
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-composer.outputs.tags }}
          labels: ${{ steps.meta-composer.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata (tags, labels) for Docker development
        id: meta-dev
        uses: docker/metadata-action@v4
        env:
          SUFFIX: dev
        with:
          images: ${{ env.REGISTRY }}
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}},suffix=-${{ env.SUFFIX }},value=${{ env.PHP_VERSION }}
            type=semver,pattern={{major}}.{{minor}},suffix=-${{ env.SUFFIX }},value=${{ env.PHP_VERSION }}
            type=semver,pattern={{major}},suffix=-${{ env.SUFFIX }},value=${{ env.PHP_VERSION }}
          labels: |
            org.opencontainers.image.title=${{ env.PHP_MAJOR }}
            org.opencontainers.image.description=${{ env.PHP_MAJOR }}
            org.opencontainers.image.source=https://github.com/anhkhoa289/anhkhoa289/php/${{ env.PHP_MAJOR }}/dockerfile.dev
            org.opencontainers.image.url=https://github.com/anhkhoa289/anhkhoa289/php/${{ env.PHP_MAJOR }}/dockerfile.dev

      - name: Build and push Docker development image
        uses: docker/build-push-action@v4
        with:
          context: anhkhoa289/php/${{ env.PHP_MAJOR }}
          file: ./anhkhoa289/php/${{ env.PHP_MAJOR }}/dockerfile.dev
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-dev.outputs.tags }}
          labels: ${{ steps.meta-dev.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata (tags, labels) for Docker laravel
        id: meta-laravel
        uses: docker/metadata-action@v4
        env:
          SUFFIX: laravel
        with:
          images: ${{ env.REGISTRY }}
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}},suffix=-${{ env.SUFFIX }},value=${{ env.PHP_VERSION }}
            type=semver,pattern={{major}}.{{minor}},suffix=-${{ env.SUFFIX }},value=${{ env.PHP_VERSION }}
            type=semver,pattern={{major}},suffix=-${{ env.SUFFIX }},value=${{ env.PHP_VERSION }}
          labels: |
            org.opencontainers.image.title=${{ env.PHP_MAJOR }}
            org.opencontainers.image.description=${{ env.PHP_MAJOR }}
            org.opencontainers.image.source=https://github.com/anhkhoa289/anhkhoa289/php/${{ env.PHP_MAJOR }}/dockerfile.laravel
            org.opencontainers.image.url=https://github.com/anhkhoa289/anhkhoa289/php/${{ env.PHP_MAJOR }}/dockerfile.laravel

      - name: Build and push Docker laravel image
        uses: docker/build-push-action@v4
        with:
          context: anhkhoa289/php/${{ env.PHP_MAJOR }}
          file: ./anhkhoa289/php/${{ env.PHP_MAJOR }}/dockerfile.laravel
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-laravel.outputs.tags }}
          labels: ${{ steps.meta-laravel.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
