name: Manual build front static nginx

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag
        required: true
        type: string

env:
  REGISTRY: anhkhoa289/front-static-nginx

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        env:
          MY_TAG: v${{ github.event.inputs.tag }}
        with:
          images: ${{ env.REGISTRY }}
          tags: |
            type=semver,pattern={{version}},value=${{ env.MY_TAG }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.MY_TAG }}
            type=semver,pattern={{major}},value=${{ env.MY_TAG }}
          labels: |
            org.opencontainers.image.title=Frontend static
            org.opencontainers.image.description=Frontend static html with nginx
            org.opencontainers.image.source=https://github.com/anhkhoa289/anhkhoa289/front-static-nginx/dockerfile
            org.opencontainers.image.url=https://github.com/anhkhoa289/anhkhoa289/front-static-nginx/dockerfile

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: anhkhoa289/front-static-nginx
          file: ./anhkhoa289/front-static-nginx/dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
