name: Manual build easy rsa

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag
        required: true
        type: string

env:
  REGISTRY: basshub/easy-rsa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker bullseye
        id: meta-bullseye
        uses: docker/metadata-action@v4
        env:
          MY_TAG: v${{ github.event.inputs.tag }}
          SUFFIX: bullseye
        with:
          images: ${{ env.REGISTRY }}
          tags: |
            type=semver,pattern={{version}},value=${{ env.MY_TAG }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.MY_TAG }}
            type=semver,pattern={{major}},value=${{ env.MY_TAG }}
            type=raw,value=${{ env.SUFFIX }}
            type=semver,pattern={{version}},suffix=-${{ env.SUFFIX }},value=${{ env.MY_TAG }}
            type=semver,pattern={{major}}.{{minor}},suffix=-${{ env.SUFFIX }},value=${{ env.MY_TAG }}
            type=semver,pattern={{major}},suffix=-${{ env.SUFFIX }},value=${{ env.MY_TAG }}
          labels: |
            org.opencontainers.image.title=Easy RSA
            org.opencontainers.image.description=Easy RSA
            org.opencontainers.image.source=https://github.com/anhkhoa289/anhkhoa289/easy-rsa/bullseye/Dockerfile
            org.opencontainers.image.url=https://github.com/anhkhoa289/anhkhoa289/easy-rsa/bullseye/Dockerfile

      - name: Build and push Docker bullseye image
        uses: docker/build-push-action@v4
        with:
          context: anhkhoa289/easy-rsa/bullseye
          file: ./anhkhoa289/easy-rsa/bullseye/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-bullseye.outputs.tags }}
          labels: ${{ steps.meta-bullseye.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata (tags, labels) for Docker alpine
        id: meta-alpine
        uses: docker/metadata-action@v4
        env:
          MY_TAG: v${{ github.event.inputs.tag }}
          SUFFIX: alpine
        with:
          images: ${{ env.REGISTRY }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=${{ env.SUFFIX }}
            type=semver,pattern={{version}},suffix=-${{ env.SUFFIX }},value=${{ env.MY_TAG }}
            type=semver,pattern={{major}}.{{minor}},suffix=-${{ env.SUFFIX }},value=${{ env.MY_TAG }}
            type=semver,pattern={{major}},suffix=-${{ env.SUFFIX }},value=${{ env.MY_TAG }}
          labels: |
            org.opencontainers.image.title=Easy RSA
            org.opencontainers.image.description=Easy RSA
            org.opencontainers.image.source=https://github.com/anhkhoa289/anhkhoa289/easy-rsa/alpine/Dockerfile
            org.opencontainers.image.url=https://github.com/anhkhoa289/anhkhoa289/easy-rsa/alpine/Dockerfile

      - name: Build and push Docker alpine image
        uses: docker/build-push-action@v4
        with:
          context: anhkhoa289/easy-rsa/alpine
          file: ./anhkhoa289/easy-rsa/alpine/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-alpine.outputs.tags }}
          labels: ${{ steps.meta-alpine.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
